export const topMeals =[
    {
        image:'images/biryani.webp',
        title:"biryani"
    },
    {
        image:"images/cookie.jpg",
        title:"cookie"
    },
     {
        image:"images/curry.jpg",
        title:"curry"
    },
     {
        image:"images/dosa.jpg",
        title:"dosa"
    },
     {
        image:"images/hamburger.jpg",
        title:"hamburger"
    },
     {
        image:"images/india.jpg",
        title:"indian dish"
    },
    {
        image:"images/mug.webp",
        title:"mug"
    },
     {
        image:"images/pani-puri.jpg",
        title:"pani-puri"
    },
   {
        image:"images/biryani.webp",
        title:"biryani"
    },
    {
        image:"images/cookie.jpg",
        title:"cookie"
    },
     {
        image:"images/curry.jpg",
        title:"curry"
    },
     {
        image:"images/dosa.jpg",
        title:"dosa"
    },
     {
        image:"images/hamburger.jpg",
        title:"hamburger"
    },
     {
        image:"images/india.jpg",
        title:"indian dish"
    },
    {
        image:"images/mug.webp",
        title:"mug"
    },
     {
        image:"images/pani-puri.jpg",
        title:"pani-puri"
    }
]